### ISSUE TITLE
关于数据集划分

### ISSUE THREAD

**Issue by lzy-whut** [yhuang1997/3D-CPS#1]
您好，在您的代码我对有标签和无标签数据的划分存在一些问题，您时候可以提供FLARE2022数据集对应的dataset.json、split_final.pkl、nnUNetPlansv2.1_plans_2D.pkl文件？
邮箱：lizongyu_123@163.com
十分感谢

**Comment by yhuang1997** [comment]
你好！这些文件都可以基于项目文件生成出来。

- `dataset.json`是用项目`dataset_convension`中[Task666_FLARE2022](https://github.com/yhuang1997/3D-CPS/tree/master/nnunet/dataset_conversion/Task666_FLARE2022.py) 和 [Task667_FLARE2022SSL](https://github.com/yhuang1997/3D-CPS/tree/master/nnunet/dataset_conversion/Task667_FLARE2022SSL.py)生成的。
- `split_final.pkl`是在[这里](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/training/network_training/nnUNetTrainerV2_SSL.py#L396)生成的。
- `nnUNetPlansv2.1_plans_2D.pkl`是在[这里](https://github.com/yhuang1997/3D-CPS/blob/master/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py)生成的。

如果还是有需要的话，我邮箱发给你。

**Comment by lzy-whut** [comment]
> 你好！这些文件都可以基于项目文件生成出来。
> 
> * `dataset.json`是用项目`dataset_convension`中[Task666_FLARE2022](https://github.com/yhuang1997/3D-CPS/tree/master/nnunet/dataset_conversion/Task666_FLARE2022.py) 和 [Task667_FLARE2022SSL](https://github.com/yhuang1997/3D-CPS/tree/master/nnunet/dataset_conversion/Task667_FLARE2022SSL.py)生成的。
> * `split_final.pkl`是在[这里](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/training/network_training/nnUNetTrainerV2_SSL.py#L396)生成的。
> * `nnUNetPlansv2.1_plans_2D.pkl`是在[这里](https://github.com/yhuang1997/3D-CPS/blob/master/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py)生成的。
> 
> 如果还是有需要的话，我邮箱发给你。

您好，因为现在没法下载FLARE2022数据集，我这边无法生成，还是麻烦您发我一份吧，麻烦您了
