### ISSUE TITLE
nnUNet_plan_and_preprocess getting super slow after finishing cropping 

### ISSUE THREAD

**Issue by steve-zeyu-zhang** [yhuang1997/3D-CPS#2]
After running `python nnUNet_plan_and_preprocess.py -t TASK_ID --ssl`

The data finished cropping and code try to generate `dataset_properties.pkl` in the cropped folder.

In the `collect_intensity_properties()` function of `class DatasetAnalyzerSSL`, 
it takes a lot of time on processing the following line

`v = p.starmap(self._get_voxels, zip(self.patient_identifiers, [mod_id] * len(self.patient_identifiers)))`

See [line 287](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L287)

I have 191 labeled data and 763 unlabeled data in total, the average shape of these data is (1,255,512,512) in the form of (c,d,h,w)

Even with a **Intel(R) Xeon(R) Platinum 8360Y CPU** on my HPC, is still takes days to process.

Is there any way to boost the data preprocessing? Thanks.

**Comment by yhuang1997** [comment]
Sorry, I know little about boosting this time-consuming data preprocessing process. In my experience, it's normal to preprocess datasets of this magnitude like yours for a few days. However, it needs to be processed once so that it won't affect the speed of training or inference stages. If you still want to speed up the preprocessing, the latest nnU-Netv2 may help you. Our repository is based on nnU-Netv1, and codes of the preprocessing part may have improved in v2 (not sure).

I hope this helps you.

**Comment by steve-zeyu-zhang** [comment]
Thanks for the prompt response.

I found something interesting.

When I switch the [_get_voxel](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L263) to the original [_get_voxels_in_foreground](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L161C9-L161C34) in [line 287](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L287C36-L287C47), and it gets much more faster!

**Is there any consequence for replacing the `_get_voxel` for semi-supervised learning based on your experience?** I bet there is some since there must be some reasons why you re-write the `_get_voxels_in_foreground` lol.

Thanks.

**Comment by steve-zeyu-zhang** [comment]
> Sorry, I know little about boosting this time-consuming data preprocessing process. In my experience, it's normal to preprocess datasets of this magnitude like yours for a few days. However, it needs to be processed once so that it won't affect the speed of training or inference stages. If you still want to speed up the preprocessing, the latest nnU-Netv2 may help you. Our repository is based on nnU-Netv1, and codes of the preprocessing part may have improved in v2 (not sure).
> 
> I hope this helps you.

**Comment by steve-zeyu-zhang** [comment]
> Sorry, I know little about boosting this time-consuming data preprocessing process. In my experience, it's normal to preprocess datasets of this magnitude like yours for a few days. However, it needs to be processed once so that it won't affect the speed of training or inference stages. If you still want to speed up the preprocessing, the latest nnU-Netv2 may help you. Our repository is based on nnU-Netv1, and codes of the preprocessing part may have improved in v2 (not sure).
> 
> I hope this helps you.

Thanks for the prompt response.

I found something interesting.

When I switch the [_get_voxel](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L263) to the original [_get_voxels_in_foreground](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L161C9-L161C34) in [line 287](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L287C36-L287C47), and it gets much more faster!

**Is there any consequence for replacing the `_get_voxel` for semi-supervised learning based on your experience?** I bet there is some since there must be some reasons why you re-write the `_get_voxels_in_foreground` lol.

Thanks.

**Comment by yhuang1997** [comment]
> > Sorry, I know little about boosting this time-consuming data preprocessing process. In my experience, it's normal to preprocess datasets of this magnitude like yours for a few days. However, it needs to be processed once so that it won't affect the speed of training or inference stages. If you still want to speed up the preprocessing, the latest nnU-Netv2 may help you. Our repository is based on nnU-Netv1, and codes of the preprocessing part may have improved in v2 (not sure).
> > I hope this helps you.
> 
> Thanks for the prompt response.
> 
> I found something interesting.
> 
> When I switch the [_get_voxel](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L263) to the original [_get_voxels_in_foreground](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L161C9-L161C34) in [line 287](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L287C36-L287C47), and it gets much more faster!
> 
> **Is there any consequence for replacing the `_get_voxel` for semi-supervised learning based on your experience?** I bet there is some since there must be some reasons why you re-write the `_get_voxels_in_foreground` lol.
> 
> Thanks.

The only difference between these two functions is considering all voxels or foreground voxels. I overwrite it because there are no masks for unlabeled data, so finding the foreground of unlabeled data is impossible. 

During this project, I also found something weird in preprocessing: All data (including unlabeled data) have masks automatically generated by nnU-Net after cropping. For labeled data, this mask is the ground truth you gave. But I'm a little vague about where are the unlabeled masks from. So you may not get any error when running the `_ get_ voxel` function for unlabeled data, but I suggest you check these 'magical masks' carefully.

Additionally, statistics information on voxel intensity calculated is just for the subsequent step of intensity normalization. You can also design your intensity normalization method to avoid this stage. Anyway, don't be bothered by this problem. I  think it has little effect on the seg performance.

**Comment by steve-zeyu-zhang** [comment]
> > > Sorry, I know little about boosting this time-consuming data preprocessing process. In my experience, it's normal to preprocess datasets of this magnitude like yours for a few days. However, it needs to be processed once so that it won't affect the speed of training or inference stages. If you still want to speed up the preprocessing, the latest nnU-Netv2 may help you. Our repository is based on nnU-Netv1, and codes of the preprocessing part may have improved in v2 (not sure).
> > > I hope this helps you.
> > 
> > 
> > Thanks for the prompt response.
> > I found something interesting.
> > When I switch the [_get_voxel](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L263) to the original [_get_voxels_in_foreground](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L161C9-L161C34) in [line 287](https://github.com/yhuang1997/3D-CPS/blob/c7c79e173e264ab62034f3d9169b273ed573aafe/nnunet/experiment_planning/DatasetAnalyzer.py#L287C36-L287C47), and it gets much more faster!
> > **Is there any consequence for replacing the `_get_voxel` for semi-supervised learning based on your experience?** I bet there is some since there must be some reasons why you re-write the `_get_voxels_in_foreground` lol.
> > Thanks.
> 
> The only difference between these two functions is considering all voxels or foreground voxels. I overwrite it because there are no masks for unlabeled data, so finding the foreground of unlabeled data is impossible.
> 
> During this project, I also found something weird in preprocessing: All data (including unlabeled data) have masks automatically generated by nnU-Net after cropping. For labeled data, this mask is the ground truth you gave. But I'm a little vague about where are the unlabeled masks from. So you may not get any error when running the `_ get_ voxel` function for unlabeled data, but I suggest you check these 'magical masks' carefully.
> 
> Additionally, statistics information on voxel intensity calculated is just for the subsequent step of intensity normalization. You can also design your intensity normalization method to avoid this stage. Anyway, don't be bothered by this problem. I think it has little effect on the seg performance.

Many thanks for the thorough answer! I'll keep an eye on those difference.

Cheers.
